global:
  smtp_smarthost: "smtp.zoho.eu:587"
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "jaroslaw.waliczek@devops-projects.pl"
  smtp_auth_password: ""

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: "default-receiver"
  routes:
    - match:
        severity: critical
      receiver: "slack-notifications"

receivers:
  - name: "default-receiver"
    email_configs:
      - to: "jaroslaw.waliczek@devops-projects.pl"

  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alerts"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
