groups:
  - name: CPU_Monitoring
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: "CPU usage is above 80% (current value is: {{ $value }}%)"
  - name: Memory_Monitoring
    rules:
      - alert: HighMemoryUsage
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 20
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: "Memory available is below 20% (current value is: {{ $value }}%)"
  - name: Disk_Monitoring
    rules:
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs",mountpoint="/"} / node_filesystem_size_bytes{fstype!="tmpfs",mountpoint="/"}) * 100 < 15
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Low disk space on {{ $labels.device }} at {{ $labels.instance }}
          description: "Disk space is below 15% on mount point {{ $labels.mountpoint }}"
  - name: Node_Monitoring
    rules:
      - alert: NodeDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
